#!/usr/bin/env node
// Generates every consumer of tokens.json so the prototype, the WinUI shell and the .NET
// core can never drift apart:
//   dist/tokens.css                                  - the HTML prototype and docs
//   ../windows/src/ClaudeOS.Shell/Themes/Tokens.xaml - the native shell
//   ../windows/src/ClaudeOS.Core/Design/Tokens.g.cs  - the core (theme resolver, chart renderer)
// Run `node build-tokens.mjs --check` in CI: it fails if a generated file is out of date.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const t = JSON.parse(readFileSync(join(here, "tokens.json"), "utf8"));
const check = process.argv.includes("--check");

const cssName = (k) => k.replace(/\./g, "-");
const pascal = (k) => k.split(/[.\-_]/).map((p) => p[0].toUpperCase() + p.slice(1)).join("");
const cssColor = (h) => {
  // #RRGGBBAA -> rgb()/rgba() so every browser agrees.
  if (h.length === 9) {
    const [r, g, b] = [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
    const a = +(parseInt(h.slice(7, 9), 16) / 255).toFixed(3);
    return `rgb(${r} ${g} ${b} / ${a})`;
  }
  return h.toLowerCase();
};
const xamlColor = (h) => (h.length === 9 ? `#${h.slice(7, 9)}${h.slice(1, 7)}` : `#FF${h.slice(1)}`).toUpperCase();

// A spring, sampled into a CSS linear() easing so web motion matches the native springs.
function springEasing({ stiffness, damping }, mass = 1) {
  const w0 = Math.sqrt(stiffness / mass);
  const zeta = damping / (2 * Math.sqrt(stiffness * mass));
  const x = (time) => {
    if (zeta < 1) {
      const wd = w0 * Math.sqrt(1 - zeta * zeta);
      return 1 - Math.exp(-zeta * w0 * time) * (Math.cos(wd * time) + (zeta * w0 / wd) * Math.sin(wd * time));
    }
    return 1 - Math.exp(-w0 * time) * (1 + w0 * time);
  };
  let end = 0.05;
  while (end < 4 && Math.abs(1 - x(end)) > 0.002) end += 0.01;
  const n = 36;
  const pts = Array.from({ length: n + 1 }, (_, i) => +x((i / n) * end).toFixed(4));
  pts[n] = 1;
  return { css: `linear(${pts.join(", ")})`, ms: Math.round(end * 1000) };
}

// ---------------------------------------------------------------- CSS
function css() {
  const L = (scope, c) => Object.entries(c).map(([k, v]) => `  --cos-${cssName(k)}: ${cssColor(v)};`).join("\n");
  const series = (mode) => t.dataviz.categorical[mode].map((c, i) => `  --cos-series-${i + 1}: ${c.toLowerCase()};`).join("\n");
  const seq = (mode) => t.dataviz.sequential[mode].map((c, i) => `  --cos-seq-${i + 1}: ${c.toLowerCase()};`).join("\n");
  const status = Object.entries(t.status).map(([k, v]) => `  --cos-status-${k}: ${v.toLowerCase()};`).join("\n");
  const fonts = Object.entries(t.font).map(([k, v]) => `  --cos-font-${k}: ${v.split(",").map((f) => (f.trim().includes(" ") ? `"${f.trim()}"` : f.trim())).join(", ")};`).join("\n");
  const sizes = Object.entries(t.size).map(([k, v]) => `  --cos-size-${k}: ${v}px;`).join("\n");
  const leading = Object.entries(t.lineHeight).map(([k, v]) => `  --cos-leading-${k}: ${v}px;`).join("\n");
  const space = Object.entries(t.space).map(([k, v]) => `  --cos-space-${k}: ${v}px;`).join("\n");
  const radius = Object.entries(t.radius).map(([k, v]) => `  --cos-radius-${k}: ${v}px;`).join("\n");
  const dur = Object.entries(t.motion.duration).map(([k, v]) => `  --cos-dur-${k}: ${v}ms;`).join("\n");
  const ease = Object.entries(t.motion.ease).map(([k, v]) => `  --cos-ease-${k}: cubic-bezier(${v.join(", ")});`).join("\n");
  const springs = Object.entries(t.motion.spring).map(([k, v]) => {
    const s = springEasing(v);
    return `  --cos-spring-${k}: ${s.css};\n  --cos-spring-${k}-dur: ${s.ms}ms;`;
  }).join("\n");
  const pres = `  --cos-breath-period: ${t.presence.breathPeriodMs}ms;\n  --cos-breath-scale: ${t.presence.breathScale};\n  --cos-orbit-period: ${t.presence.orbitPeriodMs}ms;\n  --cos-orb-size: ${t.presence.orbSize}px;\n  --cos-orb-size-large: ${t.presence.orbSizeLarge}px;`;
  const bar = `  --cos-bar-width: ${t.bar.width}px;\n  --cos-bar-height: ${t.bar.heightCollapsed}px;\n  --cos-bar-row: ${t.bar.resultRow}px;`;
  const shared = [status, fonts, sizes, leading, space, radius, dur, ease, springs, pres, bar].join("\n");
  return `/* GENERATED by design/build-tokens.mjs from design/tokens.json. Do not edit. */
:root {
  color-scheme: light dark;
${L("light", t.color.light)}
${series("light")}
${seq("light")}
  --cos-shadow-card: ${t.shadow.card};
${shared}
}
@media (prefers-color-scheme: dark) {
  :root:where(:not([data-theme="light"])) {
${L("dark", t.color.dark).replace(/^ {2}/gm, "    ")}
${series("dark").replace(/^ {2}/gm, "    ")}
    --cos-shadow-card: ${t.shadow.cardDark};
  }
}
:root[data-theme="dark"] {
  color-scheme: dark;
${L("dark", t.color.dark)}
${series("dark")}
  --cos-shadow-card: ${t.shadow.cardDark};
}
:root[data-theme="light"] { color-scheme: light; }
@media (prefers-reduced-motion: reduce) {
  :root { --cos-dur-quick: 1ms; --cos-dur-base: 1ms; --cos-dur-calm: 1ms; --cos-dur-slow: 1ms; }
}
`;
}

// ---------------------------------------------------------------- XAML
function xaml() {
  const theme = (mode) => Object.entries(t.color[mode]).map(([k, v]) => {
    const n = "Cos" + pascal(k);
    return `        <Color x:Key="${n}Color">${xamlColor(v)}</Color>\n        <SolidColorBrush x:Key="${n}Brush" Color="{StaticResource ${n}Color}" />`;
  }).concat(t.dataviz.categorical[mode].map((c, i) =>
    `        <Color x:Key="CosSeries${i + 1}Color">${xamlColor(c)}</Color>\n        <SolidColorBrush x:Key="CosSeries${i + 1}Brush" Color="{StaticResource CosSeries${i + 1}Color}" />`)).join("\n");
  const status = Object.entries(t.status).map(([k, v]) =>
    `    <Color x:Key="CosStatus${pascal(k)}Color">${xamlColor(v)}</Color>\n    <SolidColorBrush x:Key="CosStatus${pascal(k)}Brush" Color="{StaticResource CosStatus${pascal(k)}Color}" />`).join("\n");
  const doubles = (prefix, obj) => Object.entries(obj).map(([k, v]) => `    <x:Double x:Key="Cos${prefix}${pascal(k)}">${v}</x:Double>`).join("\n");
  const radii = Object.entries(t.radius).map(([k, v]) => `    <CornerRadius x:Key="CosRadius${pascal(k)}">${v}</CornerRadius>`).join("\n");
  const fonts = Object.entries(t.font).map(([k, v]) => `    <FontFamily x:Key="CosFont${pascal(k)}">${v}</FontFamily>`).join("\n");
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by design/build-tokens.mjs from design/tokens.json. Do not edit. -->
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <ResourceDictionary.ThemeDictionaries>
        <ResourceDictionary x:Key="Light">
${theme("light")}
        </ResourceDictionary>
        <ResourceDictionary x:Key="Dark">
${theme("dark")}
        </ResourceDictionary>
    </ResourceDictionary.ThemeDictionaries>

${status}
${doubles("Size", t.size)}
${doubles("Leading", t.lineHeight)}
${doubles("Space", t.space)}
${doubles("Duration", t.motion.duration)}
${radii}
${fonts}
    <x:Double x:Key="CosBarWidth">${t.bar.width}</x:Double>
    <x:Double x:Key="CosBarHeight">${t.bar.heightCollapsed}</x:Double>
    <x:Double x:Key="CosBarRow">${t.bar.resultRow}</x:Double>
    <x:Double x:Key="CosOrbSize">${t.presence.orbSize}</x:Double>
    <x:Double x:Key="CosOrbSizeLarge">${t.presence.orbSizeLarge}</x:Double>
</ResourceDictionary>
`;
}

// ---------------------------------------------------------------- C#
function cs() {
  const dict = (obj) => Object.entries(obj).map(([k, v]) => `        ["${k}"] = "${v.toUpperCase()}",`).join("\n");
  const arr = (a) => `[${a.map((c) => `"${c.toUpperCase()}"`).join(", ")}]`;
  const status = Object.entries(t.status).map(([k, v]) => `        public const string ${pascal(k)} = "${v.toUpperCase()}";`).join("\n");
  const spring = Object.entries(t.motion.spring).map(([k, v]) => `        public static readonly Spring ${pascal(k)} = new(${v.stiffness}, ${v.damping});`).join("\n");
  const dur = Object.entries(t.motion.duration).map(([k, v]) => `        public const int ${pascal(k)} = ${v};`).join("\n");
  return `// <auto-generated> by design/build-tokens.mjs from design/tokens.json. Do not edit. </auto-generated>
namespace ClaudeOS.Core.Design;

/// <summary>The default "${t.name}" theme, generated from design/tokens.json.</summary>
public static class Tokens
{
    public const string ThemeName = "${t.name}";

    public const string ThemeVersion = "${t.version}";

    public static readonly IReadOnlyDictionary<string, string> Light = new Dictionary<string, string>
    {
${dict(t.color.light)}
    };

    public static readonly IReadOnlyDictionary<string, string> Dark = new Dictionary<string, string>
    {
${dict(t.color.dark)}
    };

    public static readonly IReadOnlyList<string> SeriesLight = ${arr(t.dataviz.categorical.light)};

    public static readonly IReadOnlyList<string> SeriesDark = ${arr(t.dataviz.categorical.dark)};

    public static readonly IReadOnlyList<string> SequentialLight = ${arr(t.dataviz.sequential.light)};

    public static readonly IReadOnlyList<string> SequentialDark = ${arr(t.dataviz.sequential.dark)};

    public static class Status
    {
${status}
    }

    public static class Font
    {
        public const string Ui = "${t.font.ui}";
        public const string Display = "${t.font.display}";
        public const string Mono = "${t.font.mono}";
    }

    public static class Size
    {
${Object.entries(t.size).map(([k, v]) => `        public const int ${pascal(k)} = ${v};`).join("\n")}
    }

    public static class Radius
    {
${Object.entries(t.radius).map(([k, v]) => `        public const int ${pascal(k)} = ${v};`).join("\n")}
    }

    public static class Motion
    {
        public readonly record struct Spring(double Stiffness, double Damping);

${spring}
    }

    public static class Duration
    {
${dur}
    }

    public static class Presence
    {
        public const int BreathPeriodMs = ${t.presence.breathPeriodMs};
        public const double BreathScale = ${t.presence.breathScale};
        public const int OrbitPeriodMs = ${t.presence.orbitPeriodMs};
        public const int OrbSize = ${t.presence.orbSize};
    }

    public static class Bar
    {
        public const int Width = ${t.bar.width};
        public const int HeightCollapsed = ${t.bar.heightCollapsed};
        public const int ResultRow = ${t.bar.resultRow};
        public const int MaxRows = ${t.bar.maxRows};
    }
}
`;
}

const outputs = [
  [join(here, "dist", "tokens.css"), css()],
  [join(here, "..", "windows", "src", "ClaudeOS.Shell", "Themes", "Tokens.xaml"), xaml()],
  [join(here, "..", "windows", "src", "ClaudeOS.Core", "Design", "Tokens.g.cs"), cs()],
];

let stale = 0;
for (const [path, content] of outputs) {
  if (check) {
    if (!existsSync(path) || readFileSync(path, "utf8") !== content) {
      console.error(`stale: ${path}`);
      stale++;
    }
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`wrote ${path}`);
  }
}
if (stale) {
  console.error("Run: node design/build-tokens.mjs");
  process.exit(1);
}
