// <auto-generated> by design/build-tokens.mjs from design/tokens.json. Do not edit. </auto-generated>
namespace ClaudeOS.Core.Design;

/// <summary>The default "Calm" theme, generated from design/tokens.json.</summary>
public static class Tokens
{
    public const string ThemeName = "Calm";

    public const string ThemeVersion = "0.1.0";

    public static readonly IReadOnlyDictionary<string, string> Light = new Dictionary<string, string>
    {
        ["surface.base"] = "#FAF9F7",
        ["surface.raised"] = "#FFFFFF",
        ["surface.sunken"] = "#F2F0EC",
        ["surface.glass"] = "#FAF9F7B8",
        ["surface.scrim"] = "#1B1A1833",
        ["ink.primary"] = "#1B1A18",
        ["ink.secondary"] = "#5C5A55",
        ["ink.tertiary"] = "#6F6B64",
        ["line.hairline"] = "#1B1A1814",
        ["line.strong"] = "#1B1A1833",
        ["accent.mark"] = "#EB6834",
        ["accent.glow"] = "#FF9B6B",
        ["accent.action"] = "#BF4A1D",
        ["accent.action.ink"] = "#FFFFFF",
        ["accent.soft"] = "#EB683414",
        ["focus.ring"] = "#2A78D6",
        ["diff.add"] = "#0CA30C1F",
        ["diff.remove"] = "#D03B3B1F",
    };

    public static readonly IReadOnlyDictionary<string, string> Dark = new Dictionary<string, string>
    {
        ["surface.base"] = "#1C1B1A",
        ["surface.raised"] = "#262523",
        ["surface.sunken"] = "#151413",
        ["surface.glass"] = "#1C1B1AB8",
        ["surface.scrim"] = "#00000066",
        ["ink.primary"] = "#F4F2EE",
        ["ink.secondary"] = "#BDB9B1",
        ["ink.tertiary"] = "#9A968E",
        ["line.hairline"] = "#F4F2EE1A",
        ["line.strong"] = "#F4F2EE33",
        ["accent.mark"] = "#D95926",
        ["accent.glow"] = "#FF8A5C",
        ["accent.action"] = "#E2693A",
        ["accent.action.ink"] = "#1C1B1A",
        ["accent.soft"] = "#D959262E",
        ["focus.ring"] = "#5598E7",
        ["diff.add"] = "#0CA30C33",
        ["diff.remove"] = "#D03B3B33",
    };

    public static readonly IReadOnlyList<string> SeriesLight = ["#EB6834", "#2A78D6", "#1BAF7A", "#EDA100", "#E87BA4", "#008300", "#4A3AA7", "#E34948"];

    public static readonly IReadOnlyList<string> SeriesDark = ["#D95926", "#3987E5", "#199E70", "#C98500", "#D55181", "#008300", "#9085E9", "#E66767"];

    public static readonly IReadOnlyList<string> SequentialLight = ["#CDE2FB", "#B7D3F6", "#9EC5F4", "#86B6EF", "#6DA7EC", "#5598E7", "#3987E5", "#2A78D6", "#256ABF", "#1C5CAB", "#184F95", "#104281", "#0D366B"];

    public static readonly IReadOnlyList<string> SequentialDark = ["#CDE2FB", "#B7D3F6", "#9EC5F4", "#86B6EF", "#6DA7EC", "#5598E7", "#3987E5", "#2A78D6", "#256ABF", "#1C5CAB", "#184F95", "#104281", "#0D366B"];

    public static class Status
    {
        public const string Good = "#0CA30C";
        public const string Warning = "#FAB219";
        public const string Serious = "#EC835A";
        public const string Critical = "#D03B3B";
    }

    public static class Font
    {
        public const string Ui = "Segoe UI Variable Text, Segoe UI, Inter, system-ui, sans-serif";
        public const string Display = "Segoe UI Variable Display, Segoe UI, Inter, system-ui, sans-serif";
        public const string Mono = "Cascadia Mono, Consolas, ui-monospace, monospace";
    }

    public static class Size
    {
        public const int Caption = 12;
        public const int Body = 14;
        public const int BodyLarge = 16;
        public const int Title = 20;
        public const int Bar = 22;
        public const int Headline = 32;
        public const int Number = 40;
    }

    public static class Radius
    {
        public const int Control = 8;
        public const int Card = 12;
        public const int Window = 8;
        public const int Pill = 999;
    }

    public static class Motion
    {
        public readonly record struct Spring(double Stiffness, double Damping);

        public static readonly Spring Snappy = new(420, 34);
        public static readonly Spring Settle = new(260, 30);
        public static readonly Spring Gentle = new(170, 24);
    }

    public static class Duration
    {
        public const int Instant = 80;
        public const int Quick = 140;
        public const int Base = 220;
        public const int Calm = 360;
        public const int Slow = 600;
    }

    public static class Presence
    {
        public const int BreathPeriodMs = 4200;
        public const double BreathScale = 1.035;
        public const int OrbitPeriodMs = 2400;
        public const int OrbSize = 28;
    }

    public static class Bar
    {
        public const int Width = 720;
        public const int HeightCollapsed = 64;
        public const int ResultRow = 44;
        public const int MaxRows = 6;
    }
}
